<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-12T16:16:47 IST" name="test" finished-at="2024-04-12T16:18:17 IST" duration-ms="89631">
    <groups>
    </groups>
    <test started-at="2024-04-12T16:16:47 IST" name="Test_Edge" finished-at="2024-04-12T16:17:38 IST" duration-ms="50835">
      <class name="Test_Cases_Package.Test_Case_03">
        <test-method is-config="true" signature="BeforeClass(java.lang.String)[pri:0, instance:Test_Cases_Package.Test_Case_03@385c9627]" started-at="2024-04-12T16:16:47 IST" name="BeforeClass" finished-at="2024-04-12T16:17:35 IST" duration-ms="47330" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method signature="Test_Case_Login_Page(Test_Cases_Package.Base_Class_For_Test_cases$User_Details)[pri:0, instance:Test_Cases_Package.Test_Case_03@385c9627]" started-at="2024-04-12T16:17:35 IST" name="Test_Case_Login_Page" data-provider="Email_Password" finished-at="2024-04-12T16:17:36 IST" duration-ms="1371" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_Cases_Package.Base_Class_For_Test_cases$User_Details@3d138d4f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Case_Login_Page -->
        <test-method signature="Test_Case_Login_Page(Test_Cases_Package.Base_Class_For_Test_cases$User_Details)[pri:0, instance:Test_Cases_Package.Test_Case_03@385c9627]" started-at="2024-04-12T16:17:36 IST" name="Test_Case_Login_Page" data-provider="Email_Password" finished-at="2024-04-12T16:17:37 IST" duration-ms="775" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_Cases_Package.Base_Class_For_Test_cases$User_Details@59c2af4f]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Test_Cases_Package.Test_Case_03.Test_Case_Login_Page(Test_Case_03.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Case_Login_Page -->
        <test-method is-config="true" signature="Afterclass()[pri:0, instance:Test_Cases_Package.Test_Case_03@385c9627]" started-at="2024-04-12T16:17:37 IST" name="Afterclass" finished-at="2024-04-12T16:17:38 IST" duration-ms="1319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Afterclass -->
      </class> <!-- Test_Cases_Package.Test_Case_03 -->
    </test> <!-- Test_Edge -->
    <test started-at="2024-04-12T16:16:47 IST" name="Test_Chrome" finished-at="2024-04-12T16:18:17 IST" duration-ms="89631">
      <class name="Test_Cases_Package.Test_Case_03">
        <test-method is-config="true" signature="BeforeClass(java.lang.String)[pri:0, instance:Test_Cases_Package.Test_Case_03@33d512c1]" started-at="2024-04-12T16:16:47 IST" name="BeforeClass" finished-at="2024-04-12T16:18:14 IST" duration-ms="86840" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method signature="Test_Case_Login_Page(Test_Cases_Package.Base_Class_For_Test_cases$User_Details)[pri:0, instance:Test_Cases_Package.Test_Case_03@33d512c1]" started-at="2024-04-12T16:18:14 IST" name="Test_Case_Login_Page" data-provider="Email_Password" finished-at="2024-04-12T16:18:15 IST" duration-ms="1377" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_Cases_Package.Base_Class_For_Test_cases$User_Details@1d9586e8]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Case_Login_Page -->
        <test-method signature="Test_Case_Login_Page(Test_Cases_Package.Base_Class_For_Test_cases$User_Details)[pri:0, instance:Test_Cases_Package.Test_Case_03@33d512c1]" started-at="2024-04-12T16:18:15 IST" name="Test_Case_Login_Page" data-provider="Email_Password" finished-at="2024-04-12T16:18:16 IST" duration-ms="975" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_Cases_Package.Base_Class_For_Test_cases$User_Details@2a40925f]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Test_Cases_Package.Test_Case_03.Test_Case_Login_Page(Test_Case_03.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Case_Login_Page -->
        <test-method is-config="true" signature="Afterclass()[pri:0, instance:Test_Cases_Package.Test_Case_03@33d512c1]" started-at="2024-04-12T16:18:16 IST" name="Afterclass" finished-at="2024-04-12T16:18:17 IST" duration-ms="415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Afterclass -->
      </class> <!-- Test_Cases_Package.Test_Case_03 -->
    </test> <!-- Test_Chrome -->
  </suite> <!-- test -->
</testng-results>
